In [7]:
#Reshaping the array 2,4 to 4,2
import numpy as np
two_d_array=np.array([[1,2,3,4],[5,6,7,8]])
np.reshape(a=two_d_array,newshape=(4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
#convert multidimensional to one dimensional using ravel() 
#using Rows
np.ravel(a=two_d_array,order='C')


array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
#using Columns
np.ravel(a=two_d_array,order='F')

array([1, 5, 2, 6, 3, 7, 4, 8])

In [10]:
#Also using flatten method for the multidimensional to 1D array
two_d_array.flatten()


array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
#Transpose an array : rows to columns and columns to rows
two_d_array.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [12]:
#Flip an array horizontally : updown
np.flipud(two_d_array)

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [13]:
np.fliplr(two_d_array) #leftright

array([[4, 3, 2, 1],
       [8, 7, 6, 5]])

In [14]:
#Rotate an array 90degree
np.rot90(two_d_array,k=1)

array([[4, 8],
       [3, 7],
       [2, 6],
       [1, 5]])

In [15]:
#shift elements in an array along a given dimension
np.roll(a=two_d_array,shift=2,axis=1)

array([[3, 4, 1, 2],
       [7, 8, 5, 6]])