In [1]:
import numpy as np 
my_list=[1,2,3,4]
my_array=np.array(my_list)
type(my_array)

numpy.ndarray

In [3]:
second_list=[5,6,7,8]
two_d_array=np.array([my_list,second_list])
print(two_d_array)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
two_d_array.shape

(2, 4)

In [5]:
two_d_array.size

8

In [6]:
two_d_array.dtype

dtype('int64')

In [7]:
np.identity(n=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.ones(shape=[2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros(shape=[2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
one_d_array=np.array([1,2,3,4])
one_d_array[2]

np.int64(3)

In [12]:
one_d_array[2:]

array([3, 4])

In [13]:
one_d_array[::-1]

array([4, 3, 2, 1])